name: Release

on:
  push:
    tags:
      - 'v*' # Déclenche sur les tags qui commencent par 'v'

jobs:
  release:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write # Nécessaire pour créer des releases
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21' # Ajuste selon ta version
        
    - name: Go Release Binaries
      uses: wangyoucao577/go-release-action@v1.53
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: linux
        goarch: amd64
        binary_name: mon-app  # Change selon le nom de ton app
        asset_name: mon-app-linux-amd64